#Version del docker compose
version: '3.3'

services:
  ts-avanto-ms01:
    build:
      context: .
    container_name: avanto-ms01
    restart: always
    ports:
      - $PORT:$PORT
    networks:
      - avanto
    environment:
      - DB_HOST=$DB_HOST
      - DB_USERNAME=$DB_USERNAME
      - DB_PASSWORD=$DB_PASSWORD
      - DB_PORT=$DB_PORT
      - DB_NAME=$DB_NAME
      - DB_LOGGING=$DB_LOGGING
      - DB_SYNC=$DB_SYNC
      - DB_SCHEMA=$DB_SCHEMA
      - NODE_ENV=$NODE_ENV
      - PORT=$PORT
      - SERVICE=saas

networks:
  avanto: