apiVersion: apps/v1
kind: Deployment
metadata:
  name: nestjs-deployment
  labels:
    app: nestjs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nestjs
  template:
    metadata:
      labels:
        app: nestjs
    spec:
      containers:
      - name: nestjs
        image: 067435599643.dkr.ecr.us-east-1.amazonaws.com/micro-test2:latest
        ports:
        - containerPort: 3000
        env:
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: nestjs-secret
              key: db-user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nestjs-secret
              key: db-password
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: nestjs-config
              key: app-port
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: nestjs-config
              key: node-env
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: nestjs-config
              key: db-host
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: nestjs-config
              key: db-port
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: nestjs-config
              key: db-name
        - name: DB_LOGGING
          valueFrom:
            configMapKeyRef:
              name: nestjs-config
              key: db-logging
        - name: DB_SYNC
          valueFrom:
            configMapKeyRef:
              name: nestjs-config
              key: db-sync
        - name: DB_SCHEMA
          valueFrom:
            configMapKeyRef:
              name: nestjs-config
              key: db-schema
---
apiVersion: v1
kind: Service
metadata:
  name: nestjs-service
spec:
  type: NodePort
  selector:
    app: nestjs
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30201
